Add Gomega and Ginkgo tests
StevensSEC/pokemonbattlelib pull request #117
Opened 2021-02-20 08:39 UTC by carpenterd777

This also moves all the tests to its own package, which is apparently good practice for behavior driven design (BDD). Some unexported types needed to be exported as a result.

Closes #106

2021-02-20 08:40 UTC, carpenterd777 commented
This refactor is kinda hefty, so if I could split the tests with someone that would be great

2021-02-20 14:57 UTC, dyc3 commented on README.md
> +```
IIRC, go automatically grabs dependencies when you build anything

2021-02-20 15:24 UTC, dyc3 commented
I would prefer if we could move stuff over in smaller chunks, one test file at a time. It'll be easier to manage the transition. This PR is fine to maintain what it has in it: the `pokemon_test` and `rng_test`, as it is fairly large already.

2021-02-21 01:35 UTC, dyc3 commented
How do you run the tests? `go test` doesn't seem to work.

2021-02-21 01:47 UTC, dyc3 requested changes
So far so good, but `go test` needs to work from the top level directory, and we need to be able to collect test coverage.

I also think that the test files should stay next to the things that they are testing, instead of going in it's own folder.

2021-02-21 03:05 UTC, carpenterd777 commented
I don't think the files should stay in the top-level directory. Moving them into a subpackage not only increases organization of the project directory but ensures that we are testing only the behavior of the library instead of its implementation details.

Running the tests can be done atm by moving into the `pokemonbattlelib_test` directory and running `go test` or `ginkgo`. Is there a way to configure the tool we use for code coverage (I see it put comments on our prs)? It would be worth investigating if we can keep collecting test coverage but keep this directory structure

2021-02-21 03:18 UTC, carpenterd777 commented
This might be useful:

https://onsi.github.io/ginkgo/#ginkgo-and-continuous-integration

2021-02-21 03:24 UTC, dyc3 commented
Every other go project that I've seen puts tests next to the thing that they are testing. I see no reason to try and force something for organization if it's not easy, because it was clearly not intended to work that way. We'll probably be setting ourselves up for problems down the road.

2021-02-21 03:36 UTC, carpenterd777 commented
Try running `ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --coverpkg=github.com/StevensSEC/pokemonbattlelib --trace --race --progress --coverprofile=coverage.out --outputdir=.` with this branch checked out

2021-02-21 03:43 UTC, dyc3 commented
That works, but it's super verbose. It's going to be confusing/intimidating for beginners. I still think that we should still have the tests work with just `go test`

2021-02-21 03:51 UTC, carpenterd777 commented
If its too verbose, just `ginkgo -r` will work, or `ginkgo -r --coverpkg=github.com/StevensSEC/pokemonbattlelib --coverprofile=coverage.out --outputdir=.`. Or we can use the vscode task again

2021-02-21 04:31 UTC, dyc3 requested changes
Right now, basically all of our tests act as if they are a user of the package: by creating a battle that produces the conditions that it's testing for. The only exception I can think of off the top of my head is `apply`/`clear` for `StatusCondition`, and it's just there for the sanity check. 

If we _really, really_ want to write tests as if we are importing the package, we can do that, but the folder should be called `tests`, and we should not directly move our existing tests there.

If we decide to move different parts of the library to subpackages, it will be more cumbersome to dig through the tests folder to find the test file that we are looking for. It will be much easier if the test files are right next to the thing.

Additionally, as it stands with this implementation, this method of testing requires us to export functions that are not supposed to be exported. `getPokemon` on Battle and the `party` type were not originally intended to be exported.

I think that moving the tests to another folder is only going to cause us more pain down the line. Please put them back where they were.

Also, some tests have been commented out, which automatically makes this PR unmergable for me.

2021-02-21 04:31 UTC, dyc3 commented on pokemon.go
> +
Should go in a different PR.

2021-02-21 04:31 UTC, dyc3 commented on pokemon.go
>  	}
Bug fix, should go in a different PR.

2021-02-22 04:25 UTC, dyc3 requested changes

2021-02-22 04:25 UTC, dyc3 commented on battle.go
> +func (b *Battle) GetPokemon(party, slot int) *Pokemon {
Revert this change
```suggestion
func (b *Battle) getPokemon(party, slot int) *Pokemon {
```

2021-02-22 04:25 UTC, dyc3 commented on .vscode/tasks.json
> +				"command": "ginkgo -r --coverpkg=github.com/StevensSEC/pokemonbattlelib --coverprofile=\"coverage.out\" --outputdir=\".\" & go tool cover -html=\"coverage.out\""
Revert these changes

2021-02-22 04:25 UTC, dyc3 commented on .github/workflows/test.yml
> +      run: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --coverpkg=github.com/StevensSEC/pokemonbattlelib --trace --race --progress --coverprofile=coverage.out --outputdir=.
Revert these changes

2021-02-22 04:25 UTC, dyc3 commented on party.go
> +type Party struct {
Revert this change
```suggestion
type party struct {
```

2021-02-22 05:30 UTC, dyc3 approved these changes

2021-02-22 05:30 UTC, merged