fix: status clear
StevensSEC/pokemonbattlelib pull request #181
Opened 2021-03-02 04:52 UTC by adapap

Simple enough? Closes #174

2021-03-02 14:16 UTC, dyc3 requested changes
Doesn't have any tests. The solution is definitely not that simple.

2021-03-02 17:42 UTC, dyc3 requested changes

2021-03-02 17:42 UTC, dyc3 commented on types_test.go
> +			clear: StatusConfusion,
```suggestion
			clear: StatusFreeze,
```

2021-03-02 17:51 UTC, dyc3 requested changes
I fixed the test case for you. The solution still does not fix the bug.

2021-03-03 03:11 UTC, adapap commented
I decided to simplify the logic instead of making the status condition check more complex. It's a lot more maintainable this way IMO.

2021-03-03 04:27 UTC, dyc3 approved these changes

2021-03-03 04:41 UTC, merged