Better test messages
StevensSEC/pokemonbattlelib pull request #218
Opened 2021-03-08 17:24 UTC by adapap

- Removed HaveLen from some tests as this is implementation specific, and we already have `HaveTransaction` and `HaveTransactionsInOrder` for those tests.

2021-03-08 20:56 UTC, dyc3 requested changes
I tried changing the test "should inflict badly poisoned damage", changing the damage checked to be different, and it gave me the output:
```
Closest pokemonbattlelib.DamageTransaction (from 3 total) has 2 fields that do not match:
    - Target
    Party 0 (Slot 0) | Team 0 | Pokemon:
    Bulbasaur   Lv100
    HP: 112/200
    
    - Damage
    12
```
It should have only given one field.

I'd also like to see what the values it expected were, eg
```
Damage: got 14, expected 12
```

2021-03-08 20:56 UTC, dyc3 commented on util_test.go
> +			return fmt.Sprintf("Closest %T (from %d total) has %d fields that do not match:\n%s",
would prefer "x/y fields that do not match" or "x out of y fields that do not match"

2021-03-09 01:31 UTC, adapap commented
> It should have only given one field.

Yes, I wasn't sure how to best compare non-trivial structs involving pointers or nested structs. I think I will reuse the logic from `compareTransaction`.
> I'd also like to see what the values it expected were

Also wasn't sure the best way to represent this for larger structs without some complicated recursive strategy.

2021-03-09 01:49 UTC, adapap commented
Alright this looks sweet! Here is a sample error message:
```
Closest pokemonbattlelib.DamageTransaction (3 total) has 2/5 fields that don't match:
    - Target
    Expected: Party 1 (Slot 0) | Team 0 | Pokemon:
    Articuno    Lv1
    HP: 6/12

    Received: Party 0 (Slot 0) | Team 0 | Pokemon:
    Articuno    Lv1
    HP: 12/12

    - Damage
    Expected: 7
    Received: 6
```

2021-03-09 03:00 UTC, dyc3 requested changes
Looking good!

2021-03-09 03:00 UTC, dyc3 commented on util_test.go
> +		// }
remove commented code

2021-03-09 16:31 UTC, dyc3 approved these changes

2021-03-09 16:31 UTC, merged