Example Battle Issue #88
StevensSEC/pokemonbattlelib pull request #360
Opened 2021-04-30 01:36 UTC by rdhadda123

- Draft
- Test
- Fixed tests that checked meta last move
- Code for example battle

2021-05-01 14:40 UTC, adapap commented
Just a tip: in your issue text, you can write keywords such as closes or fixes #88, and it will automatically link that issue to this pull request (so that it closes when this is merged).

2021-05-04 02:38 UTC, dyc3 requested changes

2021-05-04 02:38 UTC, dyc3 commented on README.md
> +func ExampleBattle() {
needs to be inside a code block, with the language `go`

See: https://www.markdownguide.org/extended-syntax/#syntax-highlighting

2021-05-04 17:06 UTC, dyc3 requested changes

2021-05-04 17:06 UTC, dyc3 commented on README.md
> +~~~go
These are tildas, not backticks
```suggestion
```go
```

2021-05-04 17:06 UTC, dyc3 commented on README.md
> +~~~
```suggestion
```
```

2021-05-04 17:07 UTC, dyc3 commented
Also the tests are failing for this PR @rdhadda123

2021-05-17 21:02 UTC, dyc3 approved these changes
@rdhadda123 I went ahead and fixed up this PR for you. There was a few small issues, but they're fixed now.

2021-05-17 21:03 UTC, merged