chore: cleanup generate code to remove linting errors
StevensSEC/pokemonbattlelib pull request #53
Opened 2021-02-12 23:54 UTC by adapap

2021-02-15 18:07 UTC, carpenterd777 commented
do you want to include the updated version of `pokedex_GEN.go`?

2021-02-15 19:44 UTC, carpenterd777 commented on data/gen.go
> +	// log.Printf("current directory: %s\n", path)
```suggestion
```

2021-02-15 20:36 UTC, dyc3 requested changes

2021-02-17 02:38 UTC, carpenterd777 approved these changes

2021-02-17 03:23 UTC, dyc3 approved these changes

2021-02-17 03:24 UTC, merged